-- Schema dump generated by /schema-dump on 2026-09-16T17:27:47.710034+00:00
--
-- Captured from the live Supabase Postgres database. This is not a migrations
-- file and running it will not recreate the schema (constraints, defaults,
-- and index definitions are summarized as comments, not executable DDL in
-- every case). It exists purely as documentation, since the schema itself
-- lives only in the live database — app.py only creates/alters a handful of
-- auxiliary tables (app_config, app_users, qbo_auth, payee_correction) at
-- runtime; everything else below was created directly in Supabase.

CREATE TABLE account (
account_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
connection_id uuid NOT NULL,
source_account_id text NOT NULL,
name text NOT NULL,
type text NOT NULL,
currency character NOT NULL,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now(),
is_active boolean NOT NULL DEFAULT true,
PRIMARY KEY (account_id)
);
-- FK: account.org_id -> organization.org_id
-- FK: account.connection_id -> connection.connection_id
-- CREATE UNIQUE INDEX account_connection_id_source_account_id_key ON public.account USING btree (connection_id, source_account_id);
-- CREATE INDEX idx_account_org ON public.account USING btree (org_id);

CREATE TABLE app_config (
key text NOT NULL,
value text,
PRIMARY KEY (key)
);

CREATE TABLE app_users (
username text NOT NULL,
name text,
password_hash text,
is_admin boolean DEFAULT false,
created_at timestamp with time zone DEFAULT now(),
PRIMARY KEY (username)
);

CREATE TABLE book_txn (
txn_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
account_id uuid NOT NULL,
source_txn_id text NOT NULL,
source_txn_type text NOT NULL,
posted_date date NOT NULL,
amount numeric NOT NULL,
currency character NOT NULL,
home_amount numeric,
fx_rate numeric,
description text,
counterparty text,
reference text,
cleared_status text NOT NULL DEFAULT 'unknown'::text,
split_group_id text,
is_void boolean NOT NULL DEFAULT false,
is_deleted boolean NOT NULL DEFAULT false,
last_modified timestamp with time zone NOT NULL,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now(),
category text,
PRIMARY KEY (txn_id)
);
-- FK: book_txn.org_id -> organization.org_id
-- FK: book_txn.account_id -> account.account_id
-- CREATE UNIQUE INDEX book_txn_account_id_source_txn_type_source_txn_id_key ON public.book_txn USING btree (account_id, source_txn_type, source_txn_id);
-- CREATE INDEX idx_booktxn_match ON public.book_txn USING btree (account_id, posted_date, amount) WHERE ((is_void = false) AND (is_deleted = false));
-- CREATE INDEX idx_booktxn_cleared ON public.book_txn USING btree (account_id, cleared_status);
-- CREATE INDEX idx_book_txn_amt_date ON public.book_txn USING btree (amount, posted_date);

CREATE TABLE connection (
connection_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
source_platform text NOT NULL,
source_company_id text NOT NULL,
display_name text,
credential_ref text NOT NULL,
status text NOT NULL DEFAULT 'active'::text,
last_synced_at timestamp with time zone,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now(),
PRIMARY KEY (connection_id)
);
-- FK: connection.org_id -> organization.org_id
-- CREATE UNIQUE INDEX connection_source_platform_source_company_id_key ON public.connection USING btree (source_platform, source_company_id);
-- CREATE INDEX idx_connection_org ON public.connection USING btree (org_id);

CREATE TABLE match (
match_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
statement_id uuid NOT NULL,
status text NOT NULL DEFAULT 'proposed'::text,
match_type text NOT NULL,
confidence numeric,
amount_delta numeric NOT NULL DEFAULT 0,
notes text,
created_by text NOT NULL DEFAULT 'engine'::text,
created_at timestamp with time zone NOT NULL DEFAULT now(),
confirmed_by text,
confirmed_at timestamp with time zone,
updated_at timestamp with time zone NOT NULL DEFAULT now(),
PRIMARY KEY (match_id)
);
-- FK: match.statement_id -> statement.statement_id
-- FK: match.org_id -> organization.org_id
-- CREATE INDEX idx_match_statement ON public.match USING btree (statement_id, status);

CREATE TABLE match_book_txn (
match_id uuid NOT NULL,
txn_id uuid NOT NULL,
PRIMARY KEY (match_id, txn_id)
);
-- FK: match_book_txn.txn_id -> book_txn.txn_id
-- FK: match_book_txn.match_id -> match.match_id

CREATE TABLE match_statement_line (
match_id uuid NOT NULL,
line_id uuid NOT NULL,
PRIMARY KEY (match_id, line_id)
);
-- FK: match_statement_line.match_id -> match.match_id
-- FK: match_statement_line.line_id -> statement_line.line_id

CREATE TABLE organization (
org_id uuid NOT NULL DEFAULT gen_random_uuid(),
name text NOT NULL,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now(),
PRIMARY KEY (org_id)
);

CREATE TABLE payee_correction (
id integer NOT NULL DEFAULT nextval('payee_correction_id_seq'::regclass),
org_id uuid NOT NULL,
payee text NOT NULL,
category text NOT NULL,
created_at timestamp with time zone NOT NULL DEFAULT now(),
PRIMARY KEY (id)
);

CREATE TABLE qbo_auth (
id integer NOT NULL,
refresh_token text,
updated_at timestamp with time zone DEFAULT now(),
realm_id text,
PRIMARY KEY (id)
);

CREATE TABLE statement (
statement_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
account_id uuid NOT NULL,
period_start date NOT NULL,
period_end date NOT NULL,
opening_balance numeric NOT NULL,
closing_balance numeric NOT NULL,
currency character NOT NULL,
source_format text,
import_ref text,
created_at timestamp with time zone NOT NULL DEFAULT now(),
updated_at timestamp with time zone NOT NULL DEFAULT now(),
signed_off_at timestamp with time zone,
signed_off_by text,
snap_exact integer,
snap_fuzzy integer,
snap_m2o integer,
snap_exc integer,
snap_diff numeric,
PRIMARY KEY (statement_id)
);
-- FK: statement.org_id -> organization.org_id
-- FK: statement.account_id -> account.account_id
-- CREATE INDEX idx_statement_account ON public.statement USING btree (account_id, period_end);

CREATE TABLE statement_line (
line_id uuid NOT NULL DEFAULT gen_random_uuid(),
org_id uuid NOT NULL,
statement_id uuid NOT NULL,
posted_date date NOT NULL,
amount numeric NOT NULL,
currency character NOT NULL,
description text,
counterparty text,
reference text,
running_balance numeric,
external_id text,
dedupe_key text NOT NULL,
created_at timestamp with time zone NOT NULL DEFAULT now(),
PRIMARY KEY (line_id)
);
-- FK: statement_line.statement_id -> statement.statement_id
-- FK: statement_line.org_id -> organization.org_id
-- CREATE UNIQUE INDEX statement_line_statement_id_dedupe_key_key ON public.statement_line USING btree (statement_id, dedupe_key);
-- CREATE INDEX idx_stmtline_match ON public.statement_line USING btree (statement_id, posted_date, amount);
-- CREATE INDEX idx_stmt_line_amt_date ON public.statement_line USING btree (amount, posted_date);
